require('settings')
require('keymappings')
require('plugins/packer')

require('plugins/nvim-cmp')
require('plugins/lsp-config')
require('plugins/treesitter')
require('plugins/vimwiki')
require('plugins/nvim-lint')
require('plugins/zk-nvim')
