#!/usr/bin/env bash

yabai -m config layout         bsp

# Padding
yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10


# Float specific apps
yabai -m rule --add app="^System Settings$" manage=off
